apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-deployment
  labels:
    app: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      containers:
      - name: tailscale
        command: ["/bin/sh", "-exc", "--"]
        args: ["tailscale.sh"]      
        image: ghcr.io/katasec/tailscale:0.04
        env:
          - name: "KEY"
            value: "$(TAILSCALE_KEY)"
          - name: "ADVERTISE_ROUTES"
            value: "$(TAILSCALE_ROUTES)"
        ports:
        - containerPort: 8080
